### ISSUE TITLE
Align --api-publish and --dispatch-version options

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-cli#1059]
`hlx publish --api-publish https://adobeioruntime.net/api/v1/web/acapt/helix-services/publish@ci812 --dispatch-version=ci225`

`--api-publish` takes the full url to the publish action while `--dispatch-version` only needs the version number to construct the dispatch action url.

The dispatch url needs only the version because it is computed based on... the publish action url. See https://github.com/adobe/helix-publish/blob/master/layouts/fastly/helix.vcl#L744.

Since both actions are now package bindings inside the current wsk namespace, I think the version should be enough in both cases.

Or we simply introduce a new `--api-publish-version` option. The full publish action url is then computed based on the current namespace, predefined action name and given version.

cc @trieloff @tripodsan

**Comment by tripodsan** [comment]
It's not quite the same. the `publish` action is used to publish.
but the dispatch version is internally used by the publish-action. 

also, changing the full url of the dispatch action is not so simple, since it might also alter the backend in VCL. but we could pass (wsk) namespace/package/action....
