### ISSUE TITLE
[publish] error if github token is present

### ISSUE THREAD

**Issue by rofe** [adobe/helix-cli#1143]
**Description**
`hlx publish` throws an error during publishing with `--github-token=...`

**To Reproduce**
1. Run `hlx publish --github-token=...` on your demo project
2. See error
```
Publishing [==============================================----] updating helix-bot purge config 2.1serror: Error while running the Publish command: StatusCodeError: 403 - undefined
    at new StatusCodeError (/Users/foo/code/helix-cli/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/Users/foo/code/helix-cli/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/Users/foo/code/helix-cli/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/Users/foo/code/helix-cli/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/Users/foo/code/helix-cli/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/Users/foo/code/helix-cli/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)403 - undefined
```

**Expected behavior**
No error is throw during publishing

**Version:**
5.0.2

**Additional context**
I ran into this while testing the new private repository support.

**Comment by MarquiseRosier** [comment]
Hmmm; you want to suppress the error; or ignore it and return to publishing without updateBotConfig?

**Comment by rofe** [comment]
I guess we could... however, we should also understand why the response is forbidden...

**Comment by MarquiseRosier** [comment]
Good point;  I know there's a request sent to https://apps.project-helix.io/config/purge and when the github_token is something obviously wrong; it throws the 403; i'm guessing it has to do with not having access to the repo because of bad token

**Comment by rofe** [comment]
The token is valid, private repo access is working. But maybe it's because I created it manually and not using `hlx auth`? 🤷‍♂

**Comment by MarquiseRosier** [comment]
Hmmm ^^ agreed; another question is where are you generating the token from?

**Comment by rofe** [comment]
https://github.com/settings/tokens

**Comment by tripodsan** [comment]
As I said earlier, those are probably 2 different tokens. I'll look into it.

**Comment by MarquiseRosier** [comment]
Don't quote me on this; but i think the tokens you generate personally cannot be used for a Github app like the Helix-bot! If you look at https://github.com/settings/ there's personal tokens and then there is Github Apps

**Comment by rofe** [comment]
I see...

**Comment by tripodsan** [comment]
The problem is indeed, that when using a _personal token_, then you cannot use it to control the github app.
The token you receive from `hlx auth`, can be used by the bot to act as the user on those repositories where the bot is installed. this means, 
- if the bot is only installed on individual repositories, the token can be used to access those
- if the bot has access to all repositories, then the token can be used to access all of them

this implies, when using the bot token, the _customer_ also needs to install the bot on those repositories.

I personally find this acceptable, since it limits the scope of the repositories the token has access. the personal access token is pretty powerful, and a customer might be reluctant to configure this (well, he could create several fake accounts, for each repo...[see SO](https://stackoverflow.com/questions/31091783/can-i-get-a-github-access-token-limited-to-access-a-single-organization)).

**Comment by tripodsan** [comment]
for the problem of this issue, I suggest for now to catch the error and print some meaningful warning message. eg:

```
if (403) then
 print "The provided GITHUB_TOKEN is not authorized to act in behalf of the helix bot and can therefore not be used to update the purge config. you can generate a new token by running 'hlx auth'"
```
