### ISSUE TITLE
How to deal with large memory consuming action ?

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-cli#1403]
Some heavy operations (like parsing a 5.7k rows table and render it - see https://github.com/adobe/helix-pipeline/issues/718) fires an out of memory error: page rendering ends with a 504 Gateway Timeout.

A quick test revealed that increasing the action memory limit from 256 MB to 512 MB.

The proposal here is to increase this memory limit by default for all helix projects.

Some more options:
- make the memory limit a parameter that can be specified on `hlx deploy`
- make the whole limits https://github.com/apache/openwhisk/blob/master/docs/reference.md#system-limits configurable
While all those options are valid and might be useful at one point, we do not need them for now.

**Comment by kptdobe** [comment]
The html action starts suffering with md files of 350KB - > 1600 lines (mainly text - certainly also depends on the generated structures)

**Comment by tripodsan** [comment]
I would like to avoid raising the limits for some outliers. furthermore it rarely solves the fundamental issue. that happens if you request the same action 2 concurrently? then the 512mb also doesn't help.... I would rather try to find a way to ensure that the user-code cannot tear down the action. and be smarter on how to allocate the memory.

I guess, the table with the 5.4k rows, will also produce a HTML that would be too big? will it still fit in the 700k response limit of runtime?

**Comment by kptdobe** [comment]
https://hlxsite-kptdobe.hlx.page/test.html
The HTML is "only" 524KB (but the page is the minimum, adding any col to the table would increase the size quickly).

In the end, increasing the limit is not enough, I could reproduce the error once.
I agree this should be solved differently.

**Comment by tripodsan** [comment]
won't fix for helix 2. irrelevant for helix 3.
