### ISSUE TITLE
investigate if CORS settings can be stricted for importer [AEM-15]

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#2151]
**Description**
The Helix Importer proxies contents of arbitrary URLs via the host parameter of the QueryString. In addition, the response headers allow all origins, disabling CORS.

**Mitigation:**
At a minimum, remove the injected access-control-allow-origin HTTP header from the responses, since it should not be necessary considering the current architecture where everything is served from the same origin.

**Comment by kptdobe** [comment]
Usually, the remote site sets an `access-control-allow-origin` HTTP header. We need to get rid of it. I think simply removing it is not an option because it is then `null` and then page cannot be loaded in the iframe. We could set it to the current host  (i.e. `http://localhost:$port`) but we would also need to replace the `host` header. And hopefully this has the same behaviour. But on the other hand, the goal here is exactly to get rid of all security to be able to import the content easily. This is a dev tool, I do not see the risk.

**Comment by kptdobe** [comment]
Closing for now considering that the point of the proxy is exactly to get rid of the CORS settings... Please re-open if needed.
