### ISSUE TITLE
How to run the testPublishCmd test locally ?

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-cli#244]
I try to run the testPublishCmd tests locally but they fail:  'Provided credentials are missing or invalid' 

This brought me to those lines: https://github.com/adobe/helix-cli/blob/master/test/testPublishCmd.js#L27-L28

What is the way to run those tests ? I am supposed to replace those 2 lines by my own credentials ?!? If yes, how is this done in the CI ? What replaces the credentials on the fly ?

@tripodsan @trieloff

**Comment by tripodsan** [comment]
I think this should be set to `replay`. you only need to set the credentials, when you record new fixtures.

**Comment by trieloff** [comment]
The tests should run "as is" locally. When you have made changes, it might become necessary to re-record the fixtures. To do that:

1. remove the existing fixtures in `test/fixtures/api.fastly.com`
2. Create a new (fresh) Service Config
3. modify https://github.com/adobe/helix-cli/blob/master/test/testPublishCmd.js#L27-L28 to include your service config
4. modify https://github.com/adobe/helix-cli/blob/master/test/testPublishCmd.js#L27-L28 to include your credentials
5. Change mode in https://github.com/adobe/helix-cli/blob/9c5c3a1d87992a18494c12c5bd243ee7ae07b8f3/test/testPublishCmd.js#L85 to `record`
6. run `npm test`
7. revert step 4 and 5 (but not 3)
8. `git add test/fixtures/api.fastly.com`
9. Commit
10. Remove the Service Config again
----

Here is how it works:

when `Replay.mode == 'replay'`, each HTTP request that is made will be matched against the existing fixtures. They have been set up, so that they ignore the `Authentication` header, but as your Service Config is still in the URL, the tests can fail when the code has been changed to make requests that have never been recorded.

**Comment by kptdobe** [comment]
An import missing step: you must empty the `fixtures/api.fastly.com-442` folder.
If you run `npm test` multiple times to record different tests, be aware that request already recorded will be played from cache (record != all requests go out).
