### ISSUE TITLE
dirty-check is useless and annoying

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#326]
the purpose of the _isDirty()_ check in `hlx deploy` is, that you don't setup auto-deploy when you still have uncommitted (code) changes. 

but during development, using  `--dirty` will cause deployment to a different action, so it would also need to change the VCL. but doing so would invalidate the current deployment as well.

also, there is a trick to circumvent this check, by just committing but not pushing the changes.

### suggest:
- dirty check is only applied for auto deployments (`--auto`)
- dirty check needs to be improved to also check that the checkout is not ahead the origin

**Comment by trieloff** [comment]
The dirty check is not about preventing auto-deploy when there are uncommitted changes, as this is not that problematic. It is about not accidentally deploying an unstable development state, which might affect a production environment.

The old behaviour was to update the strain config and to create a new strain that points to the dirty actions, so that you can still test it, without accidentally (and for others invisibly) affecting deployed actions.

**Comment by trieloff** [comment]
You can force the strain using the `X-Strain` header and/or cookie right now. We could also add a request parameter.
