### ISSUE TITLE
Improve deployment logging

### ISSUE THREAD

**Issue by filmaj** [adobe/helix-cli#584]
**Is your feature request related to a problem? Please describe.**
At home I can have pretty bad internet, especially when it comes to uploading. To make matters worse, I get regular packet loss (about ~5% is pretty average for me). As such, running `hlx deploy` for me is an adventure every time. For the dev site I'm working on, a ~12 minute deploy is pretty normal for me (I roughly count about ~35MB of `.zip` files present in `.hlx/build`). 

50% of the time I just see something like the following, with only the particular JS filename changing - but not the progress bar nor the time amount displayed after the filename (`0.1s` in the below example).

```
[=========================-------------------------] deploying summary_html.js 0.1s
```

The last 50% or so of the deployment time I see something like this, with a few varying states (posted in order of seeing it in my terminal in chronological order):

```
[=============================---------------------]  577.7s
... some time later...
[=================================-----------------]  856.7s
... some time later...
[======================================------------]  632.7s
... some time later ...
[==========================================--------]  422.6s
```

For me, the progress bar is basically in two states: just over half-way done while uploading specific files, and then varying a bit while it shows time elapsed? remaining? not sure, as the seconds count in my second paste jumped up, then back down.

**Describe the solution you'd like**
I would like for the progress bar to advance consistently! I am not sure if deployment currently takes into account how large the payloads being uploaded are. If not, I would recommend we take that into account and update the progress bar with every kb uploaded.

**Comment by trieloff** [comment]
This is a bit trickier than it seems, because the [OpenWhisk client library](https://www.npmjs.com/package/openwhisk) does not emit any events during the file upload that we could use to gauge progress. The reason is that the HTTP client used by OpenWhisk ([needle](https://www.npmjs.com/package/needle)) doesn't support this either.

One thing we could do:

1. just HTTP PUT/POST the binary directly using `request`
2. use `request`'s `drain` event to listen to the file being read: https://stackoverflow.com/a/39492211/3264555

**Comment by tripodsan** [comment]
I think 2 things can help here:
1. deployment by a CI :-)
2. making smaller actions.
