### ISSUE TITLE
improve static file delivery

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#592]
looking at a typical non-binary static file trace:

```
 x-trace: vcl_recv; hlx_headers_recv; hlx_backend_recv; hlx_strain; hlx_block_recv; hlx_deny;
 hlx_allow; hlx_recv_pipeline; hlx_owner; hlx_repo; hlx_ref; hlx_root_path; 
hlx_action_root; /developer-adobe-com/c45cb8ff2613aae195c8a5ecd97b8d2da0902413/css; 
END_RECV; vcl_recv; hlx_headers_recv; hlx_backend_recv; hlx_strain; hlx_block_recv; hlx_deny; 
hlx_allow; hlx_recv_pipeline; hlx_owner; hlx_repo; hlx_ref; hlx_root_path; hlx_index; hlx_action_root;
/developer-adobe-com/c45cb8ff2613aae195c8a5ecd97b8d2da0902413/html; END_RECV; 
vcl_miss; vcl_fetch; hlx_fetch_errors; hlx_headers_fetch; RESTART; vcl_recv; hlx_headers_recv; 
hlx_backend_recv; hlx_strain; hlx_block_recv; hlx_deny; hlx_allow; hlx_recv_static; 
hlx_github_static_owner; hlx_github_static_repo; hlx_github_static_ref; hlx_github_static_root; 
END_RECV; vcl_miss; vcl_deliver; hlx_headers_deliver
```

we can see, that 3 backend requests are required to deliver the resource, which is clearly not optimal.

possible improvements:

### 1. don't invoke non existent action
we can keep a dictionary of the actions that exists and directly call `static` for non handled extensions.

### 2. consolidate code and content static handling in 1 action
currently, there is some mediocre handling of images, such as fastly will try to load them first from the content repository and if not existant, use the `static` action, which will retrieve it from the `code` repository (or even send a redirect).

it would probably be simpler to use the `static` action for both kind of content. or even consolidate **all** actions :-) this would significantly reduce the complexity of the actions and the static handling. also see #589, as only 1 request needs to be made to the backend which is either responds with the content, or redirects for larger files.

**Comment by trieloff** [comment]
+1 on weaving the static action into the template actions.

**Comment by tripodsan** [comment]
@trieloff: with the latest changes to have a helix-static service, this needs to be reviewed.
I still think, we could handle the static requests in the template actions, if we'd know the set of actions provided by the strains on the edge.

this would also _save_ 1 restart:

1. lookup action for extension via edge dict. use static as fallback if no template action is deployed for this extension.
2. invoke action
3. action firsts checks if the requested resource exists on github - if small, response, if large respond with redirect.
4. if resource does not exist, continue with normal pipeline.

alternativ to the edge dict with the actions, we create a `dispatch` action that implements the above. I think it is still faster than using an extra restart.

1. invoke dispatch action
2. dispatch action checks if content exists, if so, return result or redirect if large
3. if not, check if extension is handled by an action, if so, invoke action
4. if not, send 404 (or invoke static?)

**Comment by trieloff** [comment]
While I think this can be made to work with https://github.com/adobe/helix-publish/issues/96 and while I'd love to save one `restart` (not because they are slow, but because we can implement other things with an extra `restart`, like https://github.com/adobe/helix-publish/issues/5) I'm hesitant for a number of reasons:

1. it would break compatibility and we either have to maintain two `helix-publish` versions (one for `hlx-cli<5.0.0` and one for `hlx=cli>=5.0.0` because we now always have to check if the action exists
2. `helix-publish` would be coupled more closely to the deployment and would need to know all actions at deploy time. This means you either have to pass the map of known actions to `helix-publish` (rendering a delayed `hlx publish` impossible, because you need to keep state) or `hlx deploy` needs to update edge dictionaries (which is also hard because it needs to know *all* service configs that point to the current deployment
3. as the number of actions may differ from deployment to deployment, the edge dictionary of the known actions also must be strain specific, leading to a large number of dictionary entries (which we'd have to parse anyway, as each entry would be an array)

The important thing to note here is that:
- `restart` is cheap, especially when one or more of the requests can be cached. 
- calling a non-existent action is cheap, too (OW handles this for us)

**Comment by tripodsan** [comment]
> as the number of actions may differ from deployment to deployment, the edge dictionary of the known actions also must be strain specific, leading to a large number of dictionary entries

I agree. so I think that using a dispatch action is probably more effective.

**Comment by tripodsan** [comment]
> 1. t would break compatibility and we either have to maintain two `helix-publish` versions (one for `hlx-cli<5.0.0` and one for `hlx=cli>=5.0.0` because we now always have to check if the action exists

at one point,  we can no longer maintain backward compatiblity. there will be some dependncy on how the actions are deployed and how they are invoked from fastly...

**Comment by trieloff** [comment]
> I think that using a dispatch action is probably more effective.

Here's the challenge I see with the dispatch action:

if we want to maintain the behavior that pipeline precedes static, then the flow you've outlined:

> 1. invoke dispatch action
> 2. dispatch action checks if content exists, if so, return result or redirect if large
> 3. if not, check if extension is handled by an action, if so, invoke action
> 4. if not, send 404 (or invoke static?)

should be changed to:

1. (after no content has been found in the `content` repo), invoke the `dispatch` action
2. dispatch action tries to invoke the pipeline action and deliver the result
3. if that fails (because pipeline action itself fails, or does not exist) invoke the static action and deliver the result

This means, we always have to call the pipeline action first, which keeps the number of backend requests low, but drives up the number of action invocations, even in the best case scenario:

| Scenario                                   | Dispatch: Backend Requests | Dispatch: Action Invocations | Restart: Backend Requests | Restart: Action Invocations |
| ------------------------------------------ | -------------------------- | ---------------------------- | ------------------------- | --------------------------- |
| Pipeline Action does not exist             | 1                          | 1                            | 1                         | 0                           |
| Pipeline Action returns 404                | 1                          | 2                            | 1                         | 1                           |
| Pipeline Action returns 200                | 1                          | 2                            | 1                         | 1                           |
| Static Action returns 404 (after fallback) | 1                          | 3                            | 2                         | 2                           |
| Static Action returns 200 (after fallback) | 1                          | 3                            | 2                         | 2                           |

I guess there is no harm in trying, and if we keep the signature of the `dispatch` action compatible with the pipeline actions, then we can keep the VCL needed for https://github.com/adobe/helix-publish/issues/96 for both approaches (and take out the static fallback) once the `dispatch` action proves useful.

**Comment by tripodsan** [comment]
> * (after no content has been found in the `content` repo), invoke the `dispatch` action

no, what I meant is only consolidate the requests that read from the content-repo. i.e.

1. create a dispatch action, that:
    1. tries to read the resource raw from the content repo
    2. if not found, delegates to action or sends 404 if action does not exist.
2. if dispatch action fails, restart to try helix-static

this has the advantage, that only the giturl of the content repo needs to be sent to the dispatch action. helix-static still uses the static-repo.

**Comment by rofe** [comment]
Is this issue still relevant now that we have the `dispatch` action?

**Comment by tripodsan** [comment]
let's close it for now.
