### ISSUE TITLE
Move helix-static to separate repo, then bind it instead of deploying it

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-cli#850]
I'd suggest to change the deployment flow for `helix--static` from:

1. customer builds `helix--static` from current helix-cli version (risk of using an old version)
2. customer deploys `helix--static` into their own Runtime namespace (takes time, especially on @filmaj's home network 😉)

to:

1. `helix-static` lives in its own repository
2. CircleCI deploys `static` into the `helix` namespace, under the package name `helix-shared`, i.e. `/helix/helix-shared/static`
3. customers [bind](https://github.com/apache/incubator-openwhisk/blob/master/docs/packages.md#creating-and-using-package-bindings) (i.e. mount) the `/helix/helix-shared` package into their own namespace, so that they can run it against their own rate limits and provide it with their own credentials, but the code lifecycle is determined by us

**Comment by tripodsan** [comment]
I like the approach above, with some additions:

- add versioning, eg: `helix-shared/static@1.0.4`
- during helix-publish, add a sequence action below the action package that links to the customers shared static action. 

example:

**helix namespace**
```
/helix-shared
  static@1.0.4
  static@2.0.0
```

**customer namespace**
```
/helix-shared -> /helix/helix-shared (bound package)
/98709abcdede
  html
  static -> /customer/helix-shared/static@1.0.4 (sequence)
/13123123adadad
  html
  static -> /customer/helix-shared/static@2.0.0 (sequence)
```

this way, new versions of static can be used for new deployments (e.g. when VLC logic changes) w/o affecting existing deployments.

**Comment by trieloff** [comment]
Sounds good.

**Comment by trieloff** [comment]
The first part has been done, https://github.com/adobe/helix-static exists.

**Comment by stefan-guggisberg** [comment]
The `README` still refers to "Helix Publish" ...

**Comment by tripodsan** [comment]
(in addition to the above)

the current static is deployed to `/customer/helix--static`, which means on every deploy it is updated.
even if the cli offers a choice, which static to use, we should probably deploy the static also relative to the package, in order to harmonize the modes.

### private static deployment

**customer namespace**
```
/98709abcdede
  html
  helix--static
/13123123adadad
  html
  helix--static
```

**Comment by trieloff** [comment]
I would like to retire the use of the private static action as soon as possible without interrupting existing sites. 

As for offering customers the ability to select a particular static action version, why don't we make this part of `helix-config.yaml`, so that we can make the decision strain-specific instead of global?

```yaml
static:
  repo: helix-home
  owner: adobe
  ref: master
  action: /helix-services/static@v1
```

**Comment by tripodsan** [comment]
> why don't we make this part of `helix-config.yaml`, so that we can make the decision strain-specific instead of global?

hmm...then we don't need the linking and package binding at all. 

however, I always saw the bind+link to a deployment an improvement to the robustness of a deployed action package. if the static-action is now part of the publish config, if fear it is less consistent with the other actions and less transparent.

In this case, I would update the `action` property during the `deploy` phase, like the `package` property with the version of the `@latest` (we should not use a sequence-link, since this is exactly what we try to avoid). 

but then, how do you detect a user-enforced version? maybe by format?

```
# locked version
action: /helix/helix-services/static@v1.2.3

# auto-generated version during deploy
action: static@v1.2.3
```

---
anyways, I like the per-deploy variant better - like with the actions. there is no strain variance either....

**Comment by trieloff** [comment]
> hmm...then we don't need the linking and package binding at all.

Package binding means that the code in the `/helix/helix-services` package will be executed with the `trieloff` user permissions and rate limits. It also allows `trieloff` to provide package-specific defaults like the GH key.

**Comment by tripodsan** [comment]
> Every strain has a different action, so there is variance.

usually not. the strains deployed together have the same package reference.
until we change that, I think we really should link the static action to the same package the actions are deployed during deploy time.

make it consistent first, then think about improving the different-action-per-strain selection later.
